
###
POST http://localhost:8082/orders
Content-Type: application/json

{
  "userId": 1,
  "productId": 2,
  "productName": "alma",
  "price": 234,
  "count": 3
}

### Generate 100 user to MySQL
POST http://localhost:8082/user/generate/100

### publish Users to Kafka Topic
POST http://localhost:8082/user/publish

### Generate Orders
POST http://localhost:8082/orders/generate/100

