spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mykafkadb
    username: mykafkadbuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  kafka:
    consumer:
      group-id: kafkapoc
      auto-offset-reset: earliest
    bootstrap-servers: localhost:29092

kafkapoc:
  raworder:
    topic-name: RawOrderTopic
    messages-per-request: 10
  user:
    topic-name: UserTopic
  interestingorder:
    topic-name: InterestingOrderTopic
