#!/bin/zsh

CREATE STREAM ksqldb_raworder (ROWKEY BIGINT)
WITH (KAFKA_TOPIC='RawOrderTopic', VALUE_FORMAT='AVRO');

CREATE TABLE ksqdb_users (id BIGINT PRIMARY KEY)
WITH (KAFKA_TOPIC='UserTopic', VALUE_FORMAT='AVRO');


# SELECT *
# FROM QUERYABLE_KSQDB_USERS;

# SELECT *
# FROM KSQLDB_RAWORDER
# WINDOW TUMBLING (SIZE 1 HOUR)
# WHERE ROWTIME >= UNIX_TIMESTAMP() - 3600000
# EMIT CHANGES;

#-- stream for the last 5 min
#CREATE STREAM KSQLDB_RAWORDER_LAST_5MIN AS
#SELECT *
#FROM KSQLDB_RAWORDER
#WHERE ROWTIME >= UNIX_TIMESTAMP() - 600000;